[[redirects]]
from="/*"
to ="/index.html"
status=200

[[headers]]
for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[build.environment]
    NODE_OPTIONS = "--max_old_space_size=8192"
