export const footings = {
  F01: [
    {
      id: "F01",
      name: "Footing Type1 : Size: 1.2x1.2x0.3 ",
      start: "",
      end: "",
      duration: 0,
      cost: 0,
      numbersRequired: 16,

      strategy: "FS",
      dependencies: [],
      type: "project",
      progress: 0,
      hideChildren: false,
      parent: "F00"
    },
    {
      id: "FT01",
      name: "PCC",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "FS",
      dependencies: ["SP6"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "F01",
      resources: []
    },
    {
      id: "FT02",
      name: "Steel",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "SS",
      dependencies: ["FT01"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "F01",
      resources: []
    },
    {
      id: "FT03",
      name: "Formwork",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "FS",
      dependencies: ["FT02"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "F01",
      resources: []
    },
    {
      id: "FT04",
      name: "Concrete",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "FF",
      dependencies: ["FT03"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "F01",
      resources: []
    }
  ],

  F02: [
    {
      id: "F02",
      name: "Footings Type2 Size: 1.5x1.5x0.3",
      start: "",
      end: "",
      duration: 0,
      cost: 0,
      numbersRequired: 0,
      strategy: "FS",
      dependencies: [],
      type: "project",
      progress: 0,
      hideChildren: false,
      parent: "F00"
    },
    {
      id: "FT201",
      name: "PCC",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "FS",
      dependencies: ["SP6"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "F02",
      resources: []
    },
    {
      id: "FT202",
      name: "Steel",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "SS",
      dependencies: ["FT201"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "F02",
      resources: []
    },
    {
      id: "FT203",
      name: "Formwork",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "FS",
      dependencies: ["FT202"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "F02",
      resources: []
    },
    {
      id: "FT204",
      name: "Concrete",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "FF",
      dependencies: ["FT203"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "F02",
      resources: []
    }
  ],
  F03: [
    {
      id: "F03",
      name: "Footings Type3 Size: 1.8x1.8x0.4",
      start: "",
      end: "",
      duration: 0,
      cost: 0,
      numbersRequired: 0,
      strategy: "FS",
      dependencies: [],
      type: "project",
      progress: 0,
      hideChildren: false,
      parent: "F00"
    },
    {
      id: "FT301",
      name: "PCC",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "FS",
      dependencies: ["SP6"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "F03",
      resources: []
    },
    {
      id: "FT302",
      name: "Steel",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "SS",
      dependencies: ["FT301"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "F03",
      resources: []
    },
    {
      id: "FT303",
      name: "Formwork",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "FS",
      dependencies: ["FT302"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "F03",
      resources: []
    },
    {
      id: "FT304",
      name: "Concrete",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "FF",
      dependencies: ["FT303"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "F03",
      resources: []
    }
  ],
  F04: [
    {
      id: "F04",
      name: "Footings Type4 Size: 2.0x2.0x0.4",
      start: "",
      end: "",
      duration: 0,
      cost: 0,
      numbersRequired: 0,
      strategy: "FS",
      dependencies: [],
      type: "project",
      progress: 0,
      hideChildren: false,
      parent: "F00"
    },
    {
      id: "FT401",
      name: "PCC",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "FS",
      dependencies: ["SP6"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "F04",
      resources: []
    },
    {
      id: "FT402",
      name: "Steel",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "SS",
      dependencies: ["FT401"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "F04",
      resources: []
    },
    {
      id: "FT403",
      name: "Formwork",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "FS",
      dependencies: ["FT402"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "F04",
      resources: []
    },
    {
      id: "FT404",
      name: "Concrete",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "FF",
      dependencies: ["FT403"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "F04",
      resources: []
    }
  ],
  F05: [
    {
      id: "F05",
      name: "Footings Type5 Size: 2.5x2.5x0.4",
      start: "",
      end: "",
      duration: 0,
      cost: 0,
      numbersRequired: 1,
      strategy: "FS",
      dependencies: [],
      type: "project",
      progress: 0,
      hideChildren: false,
      parent: "F00"
    },
    {
      id: "FT501",
      name: "PCC",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "FS",
      dependencies: ["SP6"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "F05",
      resources: []
    },
    {
      id: "FT502",
      name: "Steel",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "SS",
      dependencies: ["FT501"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "F05",
      resources: []
    },
    {
      id: "FT503",
      name: "Formwork",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "FS",
      dependencies: ["FT502"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "F05",
      resources: []
    },
    {
      id: "FT504",
      name: "Concrete",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "FF",
      dependencies: ["FT503"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "F05",
      resources: []
    }
  ],
  F06: [
    {
      id: "F06",
      name: "Footings Type6 Size: 3.0x3.0x0.5",
      start: "",
      end: "",
      duration: 0,
      cost: 0,
      numbersRequired: 1,
      strategy: "FS",
      dependencies: [],
      type: "project",
      progress: 0,
      hideChildren: false,
      parent: "F00"
    },
    {
      id: "FT601",
      name: "PCC",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "FS",
      dependencies: ["SP6"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "F06",
      resources: []
    },
    {
      id: "FT602",
      name: "Steel",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "SS",
      dependencies: ["FT601"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "F06",
      resources: []
    },
    {
      id: "FT603",
      name: "Formwork",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "FS",
      dependencies: ["FT602"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "F06",
      resources: []
    },
    {
      id: "FT604",
      name: "Concrete",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "FF",
      dependencies: ["FT603"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "F06",
      resources: []
    }
  ]
};

export const plinthBeamLength = {
  PBL1: [
    {
      id: "PT1L0",
      name: "Plinth Beam Type-1 : L/2 x 0.23 x 0.23",
      start: "",
      end: "",
      duration: 0,
      cost: 0,
      numbersRequired: 6,
      strategy: "FS",
      dependencies: ["FL0"],
      type: "project",
      progress: 0,
      hideChildren: false,
      parent: "PBL"
    },
    {
      id: "PT1L1",
      name: "Stone Masonry",
      start: "",
      end: "",
      duration: 2,
      cost: 0,
      strategy: "FS",
      dependencies: ["FL0"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "PT1L0",
      resources: []
    },
    {
      id: "PT1L2",
      name: "Beam Steel",
      start: "",
      end: "",
      duration: 2,
      cost: 0,
      strategy: "FS",
      dependencies: ["PT1L1"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "PT1L0",
      resources: []
    },
    {
      id: "PT1L3",
      name: "Beam Flasework",
      start: "",
      end: "",
      duration: 2,
      cost: 0,
      strategy: "FS",
      dependencies: ["PT1L2"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "PT1L0",
      resources: []
    },
    {
      id: "PT1L4",
      name: "Beam Concrete",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "FS",
      dependencies: ["PT1L3"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "PT1L0",
      resources: []
    }
  ],

  PBL2: [
    {
      id: "PT2L0",
      name: "Plinth Beam Type-2 : L/2 x 0.26 x 0.26",
      start: "",
      end: "",
      duration: 0,
      cost: 0,
      numbersRequired: 1,
      strategy: "FS",
      dependencies: [],
      type: "project",
      progress: 0,
      hideChildren: false,
      parent: "PBL"
    },
    {
      id: "PT2L1",
      name: "Stone Masonry",
      start: "",
      end: "",
      duration: 2,
      cost: 0,
      strategy: "FS",
      dependencies: ["PT1L1"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "PT2L0",
      resources: []
    },
    {
      id: "PT2L2",
      name: "Beam Steel",
      start: "",
      end: "",
      duration: 2,
      cost: 0,
      strategy: "FS",
      dependencies: ["PT2L1"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "PT2L0",
      resources: []
    },
    {
      id: "PT2L3",
      name: "Beam Flasework",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "FS",
      dependencies: ["PT2L2"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "PT2L0",
      resources: []
    },
    {
      id: "PT2L4",
      name: "Beam Concrete",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "FS",
      dependencies: ["PT2L3"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "PT2L0",
      resources: []
    }
  ],

  PBL3: [
    {
      id: "PT3L0",
      name: "Plinth Beam Type-3 : L/2 x 0.3 x 0.3",
      start: "",
      end: "",
      duration: 0,
      cost: 0,
      numbersRequired: 0,
      strategy: "FS",
      dependencies: [],
      type: "project",
      progress: 0,
      hideChildren: false,
      parent: "PBL"
    },
    {
      id: "PT3L1",
      name: "Stone Masonry",
      start: "",
      end: "",
      duration: 2,
      cost: 0,
      strategy: "FS",
      dependencies: ["PT2L1"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "PT3L0",
      resources: []
    },
    {
      id: "PT3L2",
      name: "Beam Steel",
      start: "",
      end: "",
      duration: 2,
      cost: 0,
      strategy: "FS",
      dependencies: ["PT3L1"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "PT3L0",
      resources: []
    },
    {
      id: "PT3L3",
      name: "Beam Flasework",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "FS",
      dependencies: ["PT3L2"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "PT3L0",
      resources: []
    },
    {
      id: "PT3L4",
      name: "Beam Concrete",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "FS",
      dependencies: ["PT3L3"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "PT3L0",
      resources: []
    }
  ],

  PBL4: [
    {
      id: "PT4L0",
      name: "Plinth Beam Type-4  : L/2 x 0.3 x 0.45",
      start: "",
      end: "",
      duration: 0,
      cost: 0,
      numbersRequired: 0,
      strategy: "FS",
      dependencies: [],
      type: "project",
      progress: 0,
      hideChildren: false,
      parent: "PBL"
    },
    {
      id: "PT4L1",
      name: "Stone Masonry",
      start: "",
      end: "",
      duration: 2,
      cost: 0,
      strategy: "FS",
      dependencies: ["PT3L1"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "PT4L0",
      resources: []
    },
    {
      id: "PT4L2",
      name: "Beam Steel",
      start: "",
      end: "",
      duration: 2,
      cost: 0,
      strategy: "FS",
      dependencies: ["PT4L1"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "PT4L0",
      resources: []
    },
    {
      id: "PT4L3",
      name: "Beam Flasework",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "FS",
      dependencies: ["PT4L2"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "PT4L0",
      resources: []
    },
    {
      id: "PT4L4",
      name: "Beam Concrete",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "FS",
      dependencies: ["PT4L3"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "PT4L0",
      resources: []
    }
  ]
};
export const plinthBeamBreadth = {
  PBB1: [
    {
      id: "PT1B0",
      name: "Plinth Beam Type-1 : B/2 x 0.23 x 0.23",
      start: "",
      end: "",
      duration: 0,
      cost: 0,
      numbersRequired: 6,

      strategy: "FS",
      dependencies: [],
      type: "project",
      progress: 0,
      hideChildren: false,
      parent: "PBB"
    },
    {
      id: "PT1B1",
      name: "Stone Masonry",
      start: "",
      end: "",
      duration: 2,
      cost: 0,
      strategy: "FS",
      dependencies: ["FL0"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "PT1B0",
      resources: []
    },
    {
      id: "PT1B2",
      name: "Beam Steel",
      start: "",
      end: "",
      duration: 2,
      cost: 0,
      strategy: "FS",
      dependencies: ["PT1B1"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "PT1B0",
      resources: []
    },
    {
      id: "PT1B3",
      name: "Beam Flasework",
      start: "",
      end: "",
      duration: 2,
      cost: 0,
      strategy: "FS",
      dependencies: ["PT1B2"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "PT1B0",
      resources: []
    },
    {
      id: "PT1B4",
      name: "Beam Concrete",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "FS",
      dependencies: ["PT1B3"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "PT1B0",
      resources: []
    }
  ],

  PBB2: [
    {
      id: "PT2B0",
      name: "Plinth Beam Type-2 : B/2 x 0.26 x 0.26",
      start: "",
      end: "",
      duration: 0,
      cost: 0,
      numbersRequired: 0,
      strategy: "FS",
      dependencies: [],
      type: "project",
      progress: 0,
      hideChildren: false,
      parent: "PBB"
    },
    {
      id: "PT2B1",
      name: "Stone Masonry",
      start: "",
      end: "",
      duration: 2,
      cost: 0,
      strategy: "FS",
      dependencies: ["PT1B1"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "PT2B0",
      resources: []
    },
    {
      id: "PT2B2",
      name: "Beam Steel",
      start: "",
      end: "",
      duration: 2,
      cost: 0,
      strategy: "FS",
      dependencies: ["PT2B1"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "PT2B0",
      resources: []
    },
    {
      id: "PT2B3",
      name: "Beam Flasework",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "FS",
      dependencies: ["PT2B2"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "PT2B0",
      resources: []
    },
    {
      id: "PT2B4",
      name: "Beam Concrete",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "FS",
      dependencies: ["PT2B3"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "PT2B0",
      resources: []
    }
  ],

  PBB3: [
    {
      id: "PT3B0",
      name: "Plinth Beam Type-3 : B/2 x 0.3 x 0.3",
      start: "",
      end: "",
      duration: 0,
      cost: 0,
      numbersRequired: 0,
      strategy: "FS",
      dependencies: [],
      type: "project",
      progress: 0,
      hideChildren: false,
      parent: "PBB"
    },
    {
      id: "PT3B1",
      name: "Stone Masonry",
      start: "",
      end: "",
      duration: 2,
      cost: 0,
      strategy: "FS",
      dependencies: ["PT2B1"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "PT3B0",
      resources: []
    },
    {
      id: "PT3B2",
      name: "Beam Steel",
      start: "",
      end: "",
      duration: 2,
      cost: 0,
      strategy: "FS",
      dependencies: ["PT3B1"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "PT3B0",
      resources: []
    },
    {
      id: "PT3B3",
      name: "Beam Flasework",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "FS",
      dependencies: ["PT3B2"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "PT3B0",
      resources: []
    },
    {
      id: "PT3B4",
      name: "Beam Concrete",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "FS",
      dependencies: ["PT3B3"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "PT3B0",
      resources: []
    }
  ],

  PBB4: [
    {
      id: "PT4B0",
      name: "Plinth Beam Type-4  : B/2 x 0.3 x 0.45",
      start: "",
      end: "",
      duration: 0,
      cost: 0,
      numbersRequired: 0,
      strategy: "FS",
      dependencies: [],
      type: "project",
      progress: 0,
      hideChildren: false,
      parent: "PBB"
    },
    {
      id: "PT4B1",
      name: "Stone Masonry",
      start: "",
      end: "",
      duration: 2,
      cost: 0,
      strategy: "FS",
      dependencies: ["PT3B1"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "PT4B0",
      resources: []
    },
    {
      id: "PT4B2",
      name: "Beam Steel",
      start: "",
      end: "",
      duration: 2,
      cost: 0,
      strategy: "FS",
      dependencies: ["PT4B1"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "PT4B0",
      resources: []
    },
    {
      id: "PT4B3",
      name: "Beam Flasework",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "FS",
      dependencies: ["PT4B2"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "PT4B0",
      resources: []
    },
    {
      id: "PT4B4",
      name: "Beam Concrete",
      start: "",
      end: "",
      duration: 1,
      cost: 0,
      strategy: "FS",
      dependencies: ["PT4B3"],
      type: "task",
      progress: 0,
      hideChildren: false,
      parent: "PT4B0",
      resources: []
    }
  ]
};
