import {Task} from './interfaces'
const tasks:Task[]=[
  {
    id:'P1',
    name:'Pre-Construction',
    start:'',
    end:'',
    duration:0,
    cost:0,
    strategy:'FS',
    dependencies:[],
    type:'project',
    progress:0,
    hideChildren:true
  },
  {
    id:'P11',
    name:'Design',
    start:'',
    end:'',
    duration:0,
    cost:0,
    strategy:'FF',
    dependencies:[],
    type:'project',
    progress:0,
    hideChildren:true,
    parent:'P1'
  },
  {
    id:'P11T1',
    name:'Floor Plan Design',
    start:'',
    end:'',
    duration:10,
    cost:0,
    strategy:'SS',
    dependencies:[],
    type:'task',
    progress:0,
    hideChildren:true,
    parent:'P11'
  },
  {
    id:'P11T2',
    name:'Plot Survey',
    start:'',
    end:'',
    duration:10,
    cost:0,
    strategy:'FS',
    dependencies:['P11T1'],
    type:'task',
    progress:0,
    hideChildren:true,
    parent:'P11'
  },
  {
    id:'P12',
    name:'Issue Contract',
    start:'',
    end:'',
    duration:10,
    cost:0,
    strategy:'SF',
    dependencies:['P11'],
    type:'project',
    progress:0,
    hideChildren:true,
    parent:'P1'
  },
]
export default tasks